//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_LTW_Nhom4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string HinhAnh { get; set; }
        public int ThuTuHienThi { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
