//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_LTW_Nhom4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.LichSuVoucher = new HashSet<LichSuVoucher>();
        }
    
        public int MaDonHang { get; set; }
        public int MaNguoiDung { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string GhiChu { get; set; }
        public decimal TamTinh { get; set; }
        public decimal GiamKhuyenMai { get; set; }
        public decimal GiamVoucher { get; set; }
        public decimal TongThanhToan { get; set; }
        public string MaVoucherDaDung { get; set; }
        public string TrangThai { get; set; }
        public string LyDoHuy { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<LichSuVoucher> LichSuVoucher { get; set; }
    }
}
