//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_LTW_Nhom4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuVoucher
    {
        public int MaLichSu { get; set; }
        public int MaVoucher { get; set; }
        public int MaDonHang { get; set; }
        public int MaNguoiDung { get; set; }
        public decimal SoTienGiam { get; set; }
        public System.DateTime NgayDung { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
