//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_LTW_Nhom4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_BanTraSuaEntities : DbContext
    {
        public QL_BanTraSuaEntities()
            : base("name=QL_BanTraSuaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public DbSet<DanhMuc> DanhMuc { get; set; }
        public DbSet<DonHang> DonHang { get; set; }
        public DbSet<KhuyenMai> KhuyenMai { get; set; }
        public DbSet<LichSuVoucher> LichSuVoucher { get; set; }
        public DbSet<NguoiDung> NguoiDung { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
        public DbSet<Topping> Topping { get; set; }
        public DbSet<Voucher> Voucher { get; set; }
    }
}
