//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_LTW_Nhom4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.DonHang = new HashSet<DonHang>();
            this.LichSuVoucher = new HashSet<LichSuVoucher>();
        }
    
        public int MaNguoiDung { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string MatKhau { get; set; }
        public string DiaChi { get; set; }
        public string VaiTro { get; set; }
        public bool TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual ICollection<LichSuVoucher> LichSuVoucher { get; set; }
    }
}
