//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_LTW_Nhom4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.KhuyenMai = new HashSet<KhuyenMai>();
            this.Topping = new HashSet<Topping>();
        }
    
        public int MaSanPham { get; set; }
        public int MaDanhMuc { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public decimal GiaS { get; set; }
        public decimal GiaM { get; set; }
        public decimal GiaL { get; set; }
        public int TongLuotMua { get; set; }
        public bool LaBanChay { get; set; }
        public bool TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<KhuyenMai> KhuyenMai { get; set; }
        public virtual ICollection<Topping> Topping { get; set; }
    }
}
