//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK_LTW_Nhom4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public Voucher()
        {
            this.LichSuVoucher = new HashSet<LichSuVoucher>();
        }
    
        public int MaVoucher { get; set; }
        public string MaCode { get; set; }
        public string MoTa { get; set; }
        public string KieuGiam { get; set; }
        public decimal GiaTri { get; set; }
        public decimal DonHangToiThieu { get; set; }
        public Nullable<int> SoLuongPhatHanh { get; set; }
        public int DaDung { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<LichSuVoucher> LichSuVoucher { get; set; }
    }
}
